homeassistant:
  customize:
    switch.luz_sacada:
      icon: mdi:lightbulb-variant
      friendly_name: Luz da Sacada
    automation.balcony_lights:
      friendly_name: Acenda a luz com detector de porta

automation:
  - alias: balcony_lights
    id: '1522208581249'
    mode: restart
    trigger:
      platform: state
      entity_id: binary_sensor.1000e72240_2
      from:
        - 'on'
        - 'off'
      to:
        - 'on'
        - 'off'
    action:
      if: >
        {{ trigger.to_state.state == 'on' and
        is_state('sun.sun', 'below_horizon') }}
      then:
        - service: switch.turn_on
          target:
            entity_id: switch.luz_sacada
        - delay:
            seconds: 40
        - service: switch.turn_off
          target:
            entity_id: switch.luz_sacada
      else:
        - delay:
            minutes: 1
        - service: switch.turn_off
          target:
            entity_id: switch.luz_sacada
